# Generated by Django 5.2.1 on 2025-05-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'user')},
        ),
    ]
