/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUsComponents: typeof import('./components/home/components/AboutUsComponents.vue')['default']
    Authentication: typeof import('./components/authentication/index.vue')['default']
    ContactUsComponents: typeof import('./components/home/components/ContactUsComponents.vue')['default']
    FiledInput: typeof import('./components/filedInput.vue')['default']
    FooterComponents: typeof import('./components/home/components/FooterComponents.vue')['default']
    FraudDetectionComponents: typeof import('./components/home/components/FraudDetectionComponents.vue')['default']
    HeaderComponents: typeof import('./components/home/components/HeaderComponents.vue')['default']
    Home: typeof import('./components/home/Home.vue')['default']
    ImageSliderComponents: typeof import('./components/home/components/ImageSliderComponents.vue')['default']
    LoginApp: typeof import('./components/authentication/components/loginApp.vue')['default']
    Question: typeof import('./components/Questions/Question.vue')['default']
    Result: typeof import('./components/Result/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/authentication/components/signIn.vue')['default']
    StartExamComponents: typeof import('./components/home/components/StartExamComponents.vue')['default']
    Timer: typeof import('./components/Questions/Timer.vue')['default']
  }
}
