/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Authentication: typeof import('./components/authentication/index.vue')['default']
    FiledInput: typeof import('./components/filedInput.vue')['default']
    FooterComponents: typeof import('./components/home/components/FooterComponents.vue')['default']
    HeaderComponents: typeof import('./components/home/components/HeaderComponents.vue')['default']
    Home: typeof import('./components/home/Home.vue')['default']
    LoginApp: typeof import('./components/authentication/components/loginApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/authentication/components/signIn.vue')['default']
  }
}
